CI improvements (#38)
This PR makes a couple of improvements to the CI:
- Use https://nexte.st/ to run tests: this is the next-generation test runner for Rust projects, which has a lot of advantages over regular `cargo test`. If you want to use this locally, install it, and then use `cargo nextest run` rather than `cargo test`.
- Some improvements to the `confirm_no_std` CI job (#23), mostly just to speed it up a little bit with caching and removal of some unnecessary work.

diff --git a/.github/tools/github_actions_run_cargo b/.github/tools/github_actions_run_cargo
--- a/.github/tools/github_actions_run_cargo
+++ b/.github/tools/github_actions_run_cargo
@@ -52,6 +52,13 @@ case "$COMMAND" in
             exit 1
         fi
         ;;
+    nextest)
+        # Reads the config from .config/nextest.toml
+        if ! cargo nextest run --profile ci "$@"; then
+            echo '::error title=Tests failed::"cargo nextest run" failed'
+            exit 1
+        fi
+        ;;
     *)
         echo "Unsupported command: $COMMAND"
         exit 1
